apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-api
spec:
  selector:
    matchLabels:
      app: hash-api
  template:
    metadata:
      labels:
        app: hash-api
    spec:
      containers:
      - name: hash-api
        image: hash-api
        imagePullPolicy: IfNotPresent
        env:
          - name:  PORT
            value: "8080"
        resources:
          limits:
            memory: "64Mi"
            cpu: "128m"
        ports:
        - containerPort: 8080
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: hash-api
spec:
  selector:
    app: hash-api
  ports:
  - port: 80
    targetPort: http

